@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

GET http://{{host}}/api/todos

###

POST http://{{host}}/api/todos
content-type: application/json

{
    "text": "new todo from api"
}

###

DELETE http://{{host}}/api/todos/602c4c2bbcf06d785ae78a5e