@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}/auth
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@refreshToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQHRlc3QuY29tIiwiaWF0IjoxNjE2MTg1MTkwLCJleHAiOjE2MTYyNzE1OTB9.14QH9XyrqejnQmxug9oK9wXV7FSj8ze_EBQ-bTsZNqY"

POST http://{{host}}/token
content-type: application/json

{
    "refreshToken": {{refreshToken}}
}

###

POST http://{{host}}/login
content-type: application/json

{
    "email": "john.doe@test.com",
    "password": "pass"
}

###

POST http://{{host}}/logout
content-type: application/json

{
    "refreshToken": {{refreshToken}}
}

###

POST http://{{host}}/register
content-type: application/json

{
    "email": "john.doe@test.com",
    "password": "pass"
}
